module.exports = [
    'Abbeyleix Golf Club',
    'Ardglass Golf Club',
    'Athenry Golf Club',
    'Achill Island Golf Club',
    'Ardminnan Golf Club',
    'Athlone Golf Club',
    'Adare Golf Club',
    'Arklow Golf Club',
    'Athy Golf Club',
    'Allen Park Golf Centre',
    'Ashbourne Golf Club',
    'Aughnacloy Golf Club',
    'Ardeer Golf Club',
    'Ashfield',
    'Ardfert Golf Club',
    'Ashford Castle Golf Club',
    'Balbriggan Golf Club',
    'Ballyliffin - The Old Links',
    'Birr Golf Club',
    'Balcarrick Golf Club',
    'Ballymena Golf Club',
    'Blackbush - Blackbush Course',
    'Ballaghderreen Golf Club',
    'Ballymoney Golf Club',
    'Blackbush - Lagore Course',
    'Ballina Golf Club',
    'Ballymote Golf Club',
    'Blackbush - Thomaston Course',
    'Ballinamona Golf Club',
    'Ballyneety Golf Club',
    'Blacklion Golf Club',
    'Ballinamore Golf Club',
    'Ballyreagh Golf Club',
    'Blackwood - Hamilton Course',
    'Ballinascorney Golf Club',
    'Balmoral Golf Club',
    'Blackwood - Temple Course',
    'Ballinasloe Golf Club',
    'Baltinglass Golf Club',
    'Blainroe Golf Club',
    'Ballinlough Castle Golf Club',
    'Banbridge Golf Club',
    'Blanchardstown Golf Club',
    'Ballinrobe Golf Club',
    'Bandon Golf Club',
    'Blarney Golf Club',
    'Ballybeggan Golf Club',
    'Bangor Golf Club',
    'Bodenstown - Lady Hill Course',
    'Ballybofey & Stranorlar Golf Club',
    'Bantry Bay Golf Club',
    'Bodenstown - Old Course',
    'Ballybunion - Cashen Course',
    'Bearna Golf & Country Club',
    'Borris Golf Club',
    'Ballybunion - Old Course',
    'Beaufort Golf Resort',
    'Boyle Golf Club',
    'Ballycastle Golf Club',
    'Beaverstown Golf Club',
    'Bray Golf Club',
    'Ballyclare Golf Club',
    'Beech Park Golf Club',
    'Bright Castle Golf Club',
    'Ballyearl Golf Club',
    'Belmullet (Carne) Golf Club',
    'Brown Trout Golf Club',
    'Ballyhaunis Golf Club',
    'Belturbet Golf Club',
    'Buncrana Golf Club',
    'Ballyheigue Castle Golf Club',
    'Belvoir Park Golf Club',
    'Bundoran Golf Club',
    'Ballykisteen Golf & Country Club',
    'Benone Golf Club',
    'Burnfield House Golf Club',
    'Ballyliffin - Glashedy Course',
    'Berehaven Golf Club',
    'Bushfoot Golf Club',
    'Cabra Castle Hotel',
    'Castletroy Golf Club',
    'Connemara Isles Golf Club',
    'Cahir Park Golf Club',
    'Castlewarden Golf Club',
    'Coollattin Golf Club',
    'Cairndhu Golf Club',
    'Celbridge Golf Club',
    'Coosheen Golf Club',
    'Callan Golf Club',
    'Charlesland Golf Club',
    'Corballis Golf Club',
    'Carlow Golf Club',
    'Charleville Golf Club',
    'Cork Golf Club',
    'Carnalea Golf Club',
    'Cill Dara Golf Club',
    'Corrstown Golf Club',
    'Carrick-on-Shannon Golf Club',
    'City of Derry - Dunhugh Course',
    'County Armagh Golf Club',
    'Carrick-on-Suir Golf Club',
    'City of Derry Golf Club',
    'County Cavan Golf Club',
    'Carrickfergus Golf Club',
    'Citywest Hotel',
    'County Longford Golf Club',
    'Carrickmines Golf Club',
    'Clandeboye - Ava Course',
    'County Meath (Trim) Golf Club',
    'Carton House Golf Club',
    'Clandeboye - Dufferin Course',
    'County Sligo Golf Club',
    'Castle Barna Golf Club',
    'Claremorris Golf Club',
    'County Tipperary Golf & Country Club',
    'Castle Golf Club',
    'Cliftonville Golf Club',
    'Courtown Golf Club',
    'Castle Hume Golf Club',
    'Clones Golf Club',
    'Craddockstown Golf Club',
    'Castlebar Golf Club',
    'Clonmel Golf Club',
    'Crossgar Golf Club',
    'Castlecomer Golf Club',
    'Clontarf Golf Club',
    'Cruit Island Golf Club',
    'Castlegregory Golf Club',
    'Cloverhill Golf Club',
    'Curra West Golf Club',
    'Castleisland Golf Club',
    'Cobh Golf Club',
    'Curragh Golf Club',
    'Castlerea Golf Club',
    'Concra Wood Golf & Country Club',
    'Cushendall Golf Club',
    'Castlerock Golf Club',
    'Connemara Golf Club',
    "Deer Park - Grace O'Malley",
    'Donegal Golf Club',
    'Dun Lagohaire Golf Club',
    'Deer Park - Main Course',
    'Doneraile Golf Club',
    'Dundalk Golf Club',
    'Deer Park - Short Course',
    'Dooks Golf Club',
    'Dunfanaghy Golf Club',
    "Deer Park - St Fintan's",
    'Douglas Golf Club',
    'Dungannon Golf Club',
    'Delgany Golf Club',
    'Downpatrick Golf Club',
    'Dungarvan Golf Club',
    'Dingle (Ceann Sibeal) Golf Club',
    'Dromoland Castle Golf Club',
    'Dunloe Golf Club',
    'Djouce Mountain Golf Club',
    'Druids Glen Golf Club',
    'Dunmore Demesne Golf Club',
    'Donabate Golf Club',
    'Dublin City Golf Club',
    'Dunmore East Golf Club',
    'Donaghadee Golf Club',
    'Dublin Mountain Golf Club',
    'Dunmurry Golf Club',
    'East Clare Golf Club',
    'Elm Park Golf Club',
    'Enniscrone Golf Club',
    'East Cork Golf Club',
    'Elmgreen Golf Club',
    'Enniskillen Golf Club',
    'Edenderry Golf Club',
    'Ennis Golf Club',
    'Esker Hills Golf Club',
    'Edenmore Golf Club',
    'Enniscorthy Golf Club',
    'Edmondstown Golf Club',
    'Enniscrone Golf Club',
    'Faithlegg Golf Club',
    'Forest Little Golf Club',
    'Foyle International Golf Centre - Championship',
    'Fermoy Golf Club',
    'Fortwilliam Golf Club',
    'Foyle International Golf Centre - Woodlands',
    'Fernhill Golf Club',
    'Fota Island Golf Club',
    'Frankfield Golf Club',
    'Fintona Golf Club',
    'Foxrock Golf Club',
    'Galgorm Castle Golf Club',
    'Glengarriff Golf Club',
    'Grange Golf Club',
    'Galway Bay Golf & Country Club',
    'Glenlo Abbey Golf Club',
    'Greenacres Golf Club',
    'Galway Golf Club',
    'Glenmalure Golf Club',
    'Greencastle Golf Club',
    'Garron Tower Golf Club',
    'Gold Coast Golf Club',
    'Greenisland Golf Club',
    'Gilnahirk Golf Club',
    'Gormanstown College Golf Club',
    'Greenore Golf Club',
    'Glasson Golf Club',
    'Gort Golf Club',
    'Greystones Golf Club',
    'Glebe Golf Club',
    'Gowran Park Golf Club',
    'Gweedore Golf Club',
    'Glen of the Downs Golf Club',
    'Gracehill Golf Club',
    'Glencullen Golf Club',
    'Grange Castle Golf Club',
    'Headfort Golf Club - Headfort New Course',
    'Highfield Golf Club',
    'Hollystown - Yellow Golf Club',
    'Headfort Golf Club - Headfort Old Course',
    'Hilton Templepatrick Golf Club',
    'Hollywood Lakes Golf Club',
    "Helen's Bay Golf Club",
    'Hollystown - Blue Golf Club',
    'Holywood Golf Club',
    'Hermitage Golf Club',
    'Hollystown - Red Golf Club',
    'Howth Golf Club',
    'Kanturk Golf Club',
    "Killarney - Mahony's Point Course",
    'Kilrush Golf Club',
    'Kenmare Golf Club',
    'Killeen Golf Club',
    'Kilternan Golf Club',
    'Kilcock Golf Club',
    'Killerig Castle Golf Club',
    'Kinsale - Farrangalway Course',
    'Kilkea Castle Golf Club',
    'Killin Park Golf Club',
    'Kinsale - Ringenane Course',
    'Kilkee Golf Club',
    'Killiney Golf Club',
    'Kirkistown Castle Golf Club',
    'Kilkeel Golf Club',
    'Killorglin Golf Club',
    'Knightsbrook Golf Club',
    'Kilkenny Golf Club',
    'Killymoon Golf Club',
    'Knock Golf Club',
    'Killarney - Killeen Course',
    'Kilmashogue Golf Club',
    'Knockanally Golf Club',
    'Killarney - Lackabane Course',
    'Kilrea Golf Club',
    'Lahinch - Castle Course',
    'Leopardstown Golf Club',
    'Listowel Golf Club',
    'Lahinch - Old Course',
    'Letterkenny Golf Club',
    'Loughgall Country Park & golf course',
    'Lambeg Golf Club',
    'Limerick Golf Club',
    'Loughrea Golf Club',
    'Larne Golf Club',
    'Lisburn Golf Club',
    'Lucan Golf Club',
    'Laytown & Bettystown Golf Club',
    'Lismore Golf Club',
    'Lurgan Golf Club',
    'Lee Valley Golf & Country Club',
    'Lisselan Golf Club',
    'Luttrellstown Castle Golf Club',
    'Macroom Golf Club',
    'Marlay Park Golf Club',
    'Mount Temple Golf Club',
    'Mahee Island Golf Club',
    'Massereene Golf Club',
    'Mount Wolseley Golf Hotel & Country Club',
    'Mahon Golf Club',
    'Milltown Golf Club',
    'Mountain View Golf Club',
    'Malahide Golf Club',
    'Mitchelstown Golf Club',
    'Mountrath Golf Club',
    'Mallow Golf Club',
    'Moate Golf Club',
    'Mourne Golf Club',
    'Mallusk Golf Club',
    'Monkstown Golf Club',
    'Moyola Park Golf Club',
    'Malone Edenderry Course',
    'Moor Park Golf Club',
    'Moyvalley Golf Club',
    'Malone Golf Club',
    'Mount Bellew Golf Club',
    'Mullingar Golf Club',
    'Mannan Castle Golf Club',
    'Mount Juliet Golf & Country Club',
    'Mulranny Golf Club',
    'Manor Golf Club',
    'Mount Ober Golf Club',
    'Muskerry Golf Club',
    'Naas Golf Club',
    'New Ross Golf Club',
    'Newry Golf Club',
    'Narin & Portnoo Golf Club',
    'Newbridge Golf Club',
    'Newtownstewart Golf Club',
    'Navan Golf Club',
    'Newcastle West Golf Club',
    'North-West Golf Club',
    'Nenagh Golf Club',
    'Newlands Golf Club',
    'Nuremore Hotel Golf  & Country Club',
    'Old Conna Golf Club',
    'Omagh Golf Club',
    'Otway Golf Club',
    'Old Head of Kinsale Golf Club',
    'Ormeau Golf Club',
    'Oughterard Golf Club',
    'Palmerstown House Golf Club',
    'Portmarnock Championship Course',
    'Portstewart - Riverside Golf Club',
    'Parknasilla Golf Club',
    'Portmarnock Hotel & Golf Links',
    'Portstewart - Strand Golf Club',
    'Portadown Golf Club',
    'Portsalon Golf Club',
    'Portumna Golf Club',
    'Portarlington Golf Club',
    'Portstewart - Old Course',
    'Powerscourt Golf Club',
    'R and R Golf Course',
    'Rockmount Golf Club',
    'Roundwood Golf Club',
    'Raffeen Creek Golf Club',
    'Rockwell Golf Club',
    'Royal Belfast Golf Club',
    'Rathbane Golf Club',
    'Roe Park Resort',
    'Royal County Down - Annesley Links',
    'Rathdowney Golf Club',
    'Roganstown Hotel & CC',
    'Royal County Down - Championship Course',
    'Rathfarnham Golf Club',
    'Rosapenna Golf Club',
    'Royal Dublin Golf Club',
    'Rathmore Golf Club',
    'Roscommon Golf Club',
    'Royal Portrush - Dunluce Links',
    'Rathsallagh Golf Club',
    'Roscrea Golf Club',
    'Royal Portrush - Valley Links',
    'Redcastle Hotel & Golf Club',
    'Ross Golf Club',
    'Royal Tara Golf Club',
    'Ring of Kerry Golf Club',
    'Rosslare Golf Club',
    'Rush Golf Club',
    'Ringdufferin Golf Club',
    'Rossmore Golf Club',
    'Scrabo Golf Club',
    'Slievenamon Golf Club',
    'Stepaside Golf Club',
    'Seafield Golf Club',
    'South County Golf Club',
    'Strabane Golf Club',
    'Seapoint Golf Links',
    'South Meath Golf Club',
    'Strandhill Golf Club',
    'Shandon Park Golf Club',
    'Spa Golf Club',
    'Strokestown Golf Club',
    'Shannon Golf Club',
    'Spanish Point Golf Club',
    'Summerhill Golf Club',
    'Silverwood Golf Centre',
    "St Anne's Golf Club",
    'Sutton Golf Club',
    'Skellig Bay Golf Club',
    "St Helen's Bay Golf Club",
    'Swinford Golf Club',
    'Skerries Golf Club',
    "St Margaret's Golf Club",
    'Swords Open Golf Club',
    'Skibbereen and West Carbery Golf Club',
    'St Patricks Links Golf Club',
    'Slieve Russell Golf Club',
    'Stackstown Golf Club',
    'Tandragee Golf Club',
    'The K Club',
    'Tramore Golf Club',
    'Tara Glen Golf Club',
    'The Kerries Golf Club',
    'Trump International Golf Links & Hotel Doonbeg',
    'Temple Golf Club',
    'The Open Golf Club',
    'Tuam Golf Club',
    'Templemore Golf Club',
    'Thurles Golf Club',
    'Tubbercurry Golf Club',
    'The European Club',
    'Tipperary Golf Club',
    'Tulfarris Golf Club',
    'The Heath Golf Club',
    'Townley Hall Golf Club',
    'Tullamore Golf Club',
    'The Heritage Golf & Spa Resort',
    'Traad Ponds Golf Club',
    'Turvey Golf Club',
    'The Island Golf Club',
    'Tralee Golf Club',
    'Vartry Lakes Golf Club',
    'Virginia Golf Club',
    'Warrenpoint Golf Club',
    'Westmanstown Golf Club',
    'Woodbrook Golf Club',
    'Water Rock Golf Club',
    'Westport Golf Club',
    'Woodenbridge Golf Club',
    'Waterford Castle Golf Club',
    'Wexford Golf Club',
    'Woodlands Golf Club',
    'Waterford Golf Club',
    'Whitehead Golf Club',
    'Woodstock Golf Club',
    'Waterville Golf Links',
    'Wicklow Golf Club',
    'West Waterford Golf Club',
    'Williamstown Golf Club',
    'Youghal Golf Club'
  ]